#!/bin/bash

set -e

export PATH=/opt/Qt/5.9-static/bin:$PATH
rm -rf build/macos/*

# Vari
qmake -config release "CONFIG += release_macos build_vari"
make clean
make -j8
rm -rf build/macos/obj
cd build/macos
zip -r esc_tool_vari_macos.zip `ls | grep -v '\.zip$'`
ls | grep -v '\.zip$' | xargs rm -rf
cd ../..
